name: Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Archive Repository
        run: |
          zip -r deploy-artifact.zip .
        working-directory: ./

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: deploy-artifact
          path: deploy-artifact.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Invalidate cache
        uses: kersvers/s3-sync-with-cloudfront-invalidation@v1.0.0
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          DISTRIBUTION_ID: "EEQ20MB4Z2YNR"
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "src"

      - name: Deploy to S3
        run: |
          aws s3 sync /home/runner/work/TCRC-Frontend/TCRC-Frontend/src s3://aahil-resume-001/
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}

  smoke_test:
    runs-on: ubuntu-latest
    needs: deploy
    environment:
      name: smoke_test

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: deploy-artifact

      - name: Unzip Artifact
        run: |
          cd /home/runner/work/TCRC-Frontend/TCRC-Frontend
          unzip -o deploy-artifact.zip -d .
        shell: bash

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run
          browser: chrome
